apiVersion: v1
kind: Pod
metadata:
  name: main-project-elasticsearch
  labels:
    name: main-project-elasticsearch
spec:
  containers:
    - image: 'docker.elastic.co/elasticsearch/elasticsearch: 7.17.0'
      name: elasticsearch
      volumeMounts:
        - name: elasticsearchdata
          mountPath: /usr/share/elasticsearch/data
  volumes:
    - name: elasticsearchdata
      persistentVolumeClaim:
        claimName: elasticsearchdata
  env: 
    discovery.type : single-node
    xpack.security.enabled: "false"

---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearchdata
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi