version: '3.7'
services: 
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./models:/myfolder/models
      - ./package.json:/myfolder/package.json
      - ./swagger:/myfolder/swagger
      - ./controllers:/myfolder/controllers
    ports:
      - 3000:3000

  my-database:
    image: mongo:latest
    ports:
      - 27017:27017
